// Copy for the Abstract Astro delivery page. Generated by docs/eclipse-funnel/make-delivery.py.
export type Block = { id: string; html: string; text: string };
export type Board = { title: string; sub: string; blocks: Block[] };
export const boards: Record<'advertorial' | 'sales', Board> = {
 "advertorial": {
  "title": "Advertorial",
  "sub": "Cold traffic. Reader has never heard of a Transformation Window.",
  "blocks": [
   {
    "id": "01",
    "html": "<div class=\"strip\">ADVERTISEMENT</div>",
    "text": "ADVERTISEMENT"
   },
   {
    "id": "02",
    "html": "<div class=\"rule\"></div>",
    "text": ""
   },
   {
    "id": "03",
    "html": "<div class=\"h1\">Millions of people felt nothing on the night of the August eclipse. That’s because <span class=\"fill\">[WINDOW_STATE: it goes off in 13 days]</span>, not on August 12.</div>",
    "text": "Millions of people felt nothing on the night of the August eclipse. That’s because [WINDOW_STATE: it goes off in 13 days] , not on August 12."
   },
   {
    "id": "04",
    "html": "<div class=\"dek\">I’ve read charts for 18 years, and I’m tired of watching people get hyped up for the wrong night. So this time I’m going to tell you what actually happens, and when.</div>",
    "text": "I’ve read charts for 18 years, and I’m tired of watching people get hyped up for the wrong night. So this time I’m going to tell you what actually happens, and when."
   },
   {
    "id": "05",
    "html": "<div class=\"dek\" style=\"font-weight:700;font-size:22px;color:#2f2620\">An eclipse doesn’t do anything the night it happens. It marks a spot in your chart and waits for a planet to cross it. The days a planet is crossing it are your Transformation Window. That’s when your life moves. Yours lasts 12 days.</div>",
    "text": "An eclipse doesn’t do anything the night it happens. It marks a spot in your chart and waits for a planet to cross it. The days a planet is crossing it are your Transformation Window. That’s when your life moves. Yours lasts 12 days."
   },
   {
    "id": "06",
    "html": "<div class=\"byline\"><div class=\"avatar\">NK</div><div class=\"lab\">By Nora Keating, astrologer</div></div>",
    "text": "NK By Nora Keating, astrologer"
   },
   {
    "id": "07",
    "html": "<div class=\"img\" style=\"height:400px\">Image</div>",
    "text": "Image"
   },
   {
    "id": "08",
    "html": "<div style=\"height:2px;background:#2f2620\"></div>",
    "text": ""
   },
   {
    "id": "09",
    "html": "<div class=\"sh\">Every few months, life goes your way for 2 weeks. That’s not luck.</div>",
    "text": "Every few months, life goes your way for 2 weeks. That’s not luck."
   },
   {
    "id": "10",
    "html": "<p class=\"p\">The long stretch where you did everything right and still got nowhere. Then, out of nowhere, a couple of weeks where the job came through, or the money showed up, or the person you’d given up on finally called.</p>",
    "text": "The long stretch where you did everything right and still got nowhere. Then, out of nowhere, a couple of weeks where the job came through, or the money showed up, or the person you’d given up on finally called."
   },
   {
    "id": "11",
    "html": "<p class=\"p\">Afterward you probably called it luck. Then you spent months trying to get it back by doing more of whatever you were doing at the time.</p>",
    "text": "Afterward you probably called it luck. Then you spent months trying to get it back by doing more of whatever you were doing at the time."
   },
   {
    "id": "12",
    "html": "<p class=\"p\">I’ve heard that story across my table hundreds of times. The good stretch was almost never something they did. It had a day it opened and a day it closed, and both were sitting in their chart long before it showed up.</p>",
    "text": "I’ve heard that story across my table hundreds of times. The good stretch was almost never something they did. It had a day it opened and a day it closed, and both were sitting in their chart long before it showed up."
   },
   {
    "id": "13",
    "html": "<p class=\"p\"><strong>That good stretch is called a Transformation Window. You get 3 or 4 a year, they’re the only weeks when pushing actually pays, and they don’t wait for you to notice. Miss one and it’s back to pushing uphill until the next one opens.</strong></p>",
    "text": "That good stretch is called a Transformation Window. You get 3 or 4 a year, they’re the only weeks when pushing actually pays, and they don’t wait for you to notice. Miss one and it’s back to pushing uphill until the next one opens."
   },
   {
    "id": "14",
    "html": "<div class=\"sh\">The eclipse that did nothing for me, then changed my whole life 11 weeks later</div>",
    "text": "The eclipse that did nothing for me, then changed my whole life 11 weeks later"
   },
   {
    "id": "15",
    "html": "<p class=\"p\">Years ago, an eclipse landed on my Moon. That’s the part of a chart that’s about your home. So I sat in the backyard until 2am waiting for something to happen. Nothing did. Not that night, not that month. I figured I’d read my own chart wrong and let it go.</p>",
    "text": "Years ago, an eclipse landed on my Moon. That’s the part of a chart that’s about your home. So I sat in the backyard until 2am waiting for something to happen. Nothing did. Not that night, not that month. I figured I’d read my own chart wrong and let it go."
   },
   {
    "id": "16",
    "html": "<p class=\"p\">11 weeks later my landlord sold the building and gave me 30 days to get out. I thought that was the eclipse finally hitting, and hitting bad.</p>",
    "text": "11 weeks later my landlord sold the building and gave me 30 days to get out. I thought that was the eclipse finally hitting, and hitting bad."
   },
   {
    "id": "17",
    "html": "<p class=\"p\">It wasn’t bad. The only desk I could afford was in a shared office across town, and the woman at the next desk sent me my first 4 paying clients. Two of them are still with me 18 years later. That office is the reason I do this for a living.</p>",
    "text": "It wasn’t bad. The only desk I could afford was in a shared office across town, and the woman at the next desk sent me my first 4 paying clients. Two of them are still with me 18 years later. That office is the reason I do this for a living."
   },
   {
    "id": "18",
    "html": "<p class=\"p\">When I looked it up afterward, Mars had crossed the eclipse spot in my chart the same week my landlord called.</p>",
    "text": "When I looked it up afterward, Mars had crossed the eclipse spot in my chart the same week my landlord called."
   },
   {
    "id": "19",
    "html": "<p class=\"p\"><strong>The eclipse did nothing the night it happened. It opened a window 11 weeks later, and I walked through it by accident. Getting lucky once is nice. Knowing the window is open, and knowing what it’s for, is a completely different thing. I’ve spent every year since finding those windows ahead of time so nobody I work with has to rely on luck.</strong></p>",
    "text": "The eclipse did nothing the night it happened. It opened a window 11 weeks later, and I walked through it by accident. Getting lucky once is nice. Knowing the window is open, and knowing what it’s for, is a completely different thing. I’ve spent every year since finding those windows ahead of time so nobody I work with has to rely on luck."
   },
   {
    "id": "20",
    "html": "<div class=\"sh\">What actually happened on August 12, and why millions of people felt nothing</div>",
    "text": "What actually happened on August 12, and why millions of people felt nothing"
   },
   {
    "id": "21",
    "html": "<p class=\"p\">An eclipse doesn’t go off. It sets a timer. On August 12 it landed on 20 degrees of Leo. That’s one spot out of 360. And on the day itself, there wasn’t a single planet anywhere near it. Nothing was going to happen that night. Anyone with a chart open could see it.</p>",
    "text": "An eclipse doesn’t go off. It sets a timer. On August 12 it landed on 20 degrees of Leo. That’s one spot out of 360. And on the day itself, there wasn’t a single planet anywhere near it. Nothing was going to happen that night. Anyone with a chart open could see it."
   },
   {
    "id": "22",
    "html": "<p class=\"p\">Every app and every horoscope posted about it anyway, because the day of the eclipse is the day people are paying attention. Millions were told to set an intention, light a candle, write it down. There was nothing there to catch it.</p>",
    "text": "Every app and every horoscope posted about it anyway, because the day of the eclipse is the day people are paying attention. Millions were told to set an intention, light a candle, write it down. There was nothing there to catch it."
   },
   {
    "id": "23",
    "html": "<p class=\"p\">“Big night tonight” gets shared a million times. “Something opens in 7 weeks, and only if you know your chart” doesn’t. So you got the first one.</p>",
    "text": "“Big night tonight” gets shared a million times. “Something opens in 7 weeks, and only if you know your chart” doesn’t. So you got the first one."
   },
   {
    "id": "24",
    "html": "<p class=\"p\">Then the week after was a week like any other, and a lot of those people decided this stuff doesn’t work. It does work. They were handed the wrong night.</p>",
    "text": "Then the week after was a week like any other, and a lot of those people decided this stuff doesn’t work. It does work. They were handed the wrong night."
   },
   {
    "id": "25",
    "html": "<p class=\"p\"><strong>If you were one of them, you didn’t miss your turn in August. Your turn hadn’t come up yet.</strong></p>",
    "text": "If you were one of them, you didn’t miss your turn in August. Your turn hadn’t come up yet."
   },
   {
    "id": "26",
    "html": "<div class=\"sh\">One Transformation Window has already come and gone since the eclipse</div>",
    "text": "One Transformation Window has already come and gone since the eclipse"
   },
   {
    "id": "27",
    "html": "<p class=\"p\"><strong>Mercury crossed the spot on August 20 and was gone by the next morning.</strong> Twenty hours, start to finish, and it was over before anyone noticed it had started.</p>",
    "text": "Mercury crossed the spot on August 20 and was gone by the next morning. Twenty hours, start to finish, and it was over before anyone noticed it had started."
   },
   {
    "id": "28",
    "html": "<p class=\"p\">If something came up in the third week of August and then fizzled before you could do anything about it, that was the window closing while you were still making up your mind.</p>",
    "text": "If something came up in the third week of August and then fizzled before you could do anything about it, that was the window closing while you were still making up your mind."
   },
   {
    "id": "29",
    "html": "<p class=\"p\">Chances are nobody told you about it. Not the apps, not the horoscope, not the accounts that spent all of August calling the eclipse your moment. I’m telling you now because that one is behind you, and the one in front of you is 14 times longer.</p>",
    "text": "Chances are nobody told you about it. Not the apps, not the horoscope, not the accounts that spent all of August calling the eclipse your moment. I’m telling you now because that one is behind you, and the one in front of you is 14 times longer."
   },
   {
    "id": "30",
    "html": "<div class=\"wrow\"><div class=\"wn\">AUG 20–21</div><div class=\"wd\">20 hours</div><div class=\"wsGone\">GONE</div></div>",
    "text": "AUG 20–21 20 hours GONE"
   },
   {
    "id": "31",
    "html": "<div class=\"wrow\"><div class=\"wn\"><span class=\"fill\">[WINDOW_STATE: IN 13 DAYS]</span></div><div class=\"wd\">12 days · Jupiter · next one in 2038</div><div class=\"wsLive\">STILL AHEAD OF YOU</div></div>",
    "text": "[WINDOW_STATE: IN 13 DAYS] 12 days · Jupiter · next one in 2038 STILL AHEAD OF YOU"
   },
   {
    "id": "32",
    "html": "<div class=\"sh\">The next planet to cross your spot is Jupiter, the one that says yes. It comes around once every 12 years.</div>",
    "text": "The next planet to cross your spot is Jupiter, the one that says yes. It comes around once every 12 years."
   },
   {
    "id": "33",
    "html": "<p class=\"p\">Saturn takes something away before it gives anything back. Mars starts a fight and calls it progress. Jupiter is the one every astrologer alive tells you to save your biggest ask for.</p>",
    "text": "Saturn takes something away before it gives anything back. Mars starts a fight and calls it progress. Jupiter is the one every astrologer alive tells you to save your biggest ask for."
   },
   {
    "id": "34",
    "html": "<p class=\"p\">It’s also slow. It takes 12 years to make it all the way around. It last crossed this spot in the fall of 2014, and it won’t be back until <strong>2038</strong>.</p>",
    "text": "It’s also slow. It takes 12 years to make it all the way around. It last crossed this spot in the fall of 2014, and it won’t be back until 2038 ."
   },
   {
    "id": "35",
    "html": "<p class=\"p\"><span class=\"fill\">[WINDOW_STATE: It opens in 13 days]</span>, it stays open for 12, and then it’s gone.</p>",
    "text": "[WINDOW_STATE: It opens in 13 days] , it stays open for 12, and then it’s gone."
   },
   {
    "id": "36",
    "html": "<p class=\"p\"><strong>12 days out of 12 years. If I could pick which planet showed up for you, I’d pick this one.</strong></p>",
    "text": "12 days out of 12 years. If I could pick which planet showed up for you, I’d pick this one."
   },
   {
    "id": "37",
    "html": "<div class=\"sh\">What your Transformation Window is actually for</div>",
    "text": "What your Transformation Window is actually for"
   },
   {
    "id": "38",
    "html": "<p class=\"p\">A window doesn’t drop anything in your lap. What it does is make people say yes more easily. For 12 days, whatever you ask for gets a warmer answer than it would any other month of the year.</p>",
    "text": "A window doesn’t drop anything in your lap. What it does is make people say yes more easily. For 12 days, whatever you ask for gets a warmer answer than it would any other month of the year."
   },
   {
    "id": "39",
    "html": "<p class=\"p\">The conversation you’ve been putting off. The thing you’ve wanted to ask for and haven’t, because you were sure the answer would be no. The person you keep meaning to reach out to. The change you keep saying you’ll make next year.</p>",
    "text": "The conversation you’ve been putting off. The thing you’ve wanted to ask for and haven’t, because you were sure the answer would be no. The person you keep meaning to reach out to. The change you keep saying you’ll make next year."
   },
   {
    "id": "40",
    "html": "<p class=\"p\">Ask in an ordinary month and you’re on your own. Ask inside the window and you’ve got the tide behind you.</p>",
    "text": "Ask in an ordinary month and you’re on your own. Ask inside the window and you’ve got the tide behind you."
   },
   {
    "id": "41",
    "html": "<p class=\"p\"><strong>That’s the wave. Stand in the right spot when it comes in, and it does most of the work for you.</strong></p>",
    "text": "That’s the wave. Stand in the right spot when it comes in, and it does most of the work for you."
   },
   {
    "id": "42",
    "html": "<div class=\"sh\">Your best day to go for it is also the worst day to make anything final</div>",
    "text": "Your best day to go for it is also the worst day to make anything final"
   },
   {
    "id": "43",
    "html": "<p class=\"p\">A few hours before Jupiter hits its strongest point, Venus stops, turns around, and goes backward for 6 weeks.</p>",
    "text": "A few hours before Jupiter hits its strongest point, Venus stops, turns around, and goes backward for 6 weeks."
   },
   {
    "id": "44",
    "html": "<p class=\"p\"><strong>Jupiter is for going after it.</strong> Asking, putting yourself out there, letting people see what you want.</p>",
    "text": "Jupiter is for going after it. Asking, putting yourself out there, letting people see what you want."
   },
   {
    "id": "45",
    "html": "<p class=\"p\"><strong>Venus is for locking it in.</strong> The promise, the commitment, the yes you can’t take back. And anything you lock in while Venus is going backward has a way of coming undone.</p>",
    "text": "Venus is for locking it in. The promise, the commitment, the yes you can’t take back. And anything you lock in while Venus is going backward has a way of coming undone."
   },
   {
    "id": "46",
    "html": "<p class=\"p\">I’ve watched more people lose to that one mix-up than to missing a window altogether. Go for it on the right day, then hold off on making it final until Venus turns back around.</p>",
    "text": "I’ve watched more people lose to that one mix-up than to missing a window altogether. Go for it on the right day, then hold off on making it final until Venus turns back around."
   },
   {
    "id": "47",
    "html": "<div style=\"height:2px;background:#2f2620\"></div>",
    "text": ""
   },
   {
    "id": "48",
    "html": "<div class=\"sh\">Your birth chart says which part of your life this window is about</div>",
    "text": "Your birth chart says which part of your life this window is about"
   },
   {
    "id": "49",
    "html": "<p class=\"p\">The eclipse hit one spot in the sky, and that spot sits somewhere different in every chart. For one person it lands on the part that’s about work. For the next it’s the part that’s about home, or money, or one particular person. Same window, completely different life.</p>",
    "text": "The eclipse hit one spot in the sky, and that spot sits somewhere different in every chart. For one person it lands on the part that’s about work. For the next it’s the part that’s about home, or money, or one particular person. Same window, completely different life."
   },
   {
    "id": "50",
    "html": "<p class=\"p\">Your chart answers three questions, and they’re the difference between using this window and sleeping through it.</p>",
    "text": "Your chart answers three questions, and they’re the difference between using this window and sleeping through it."
   },
   {
    "id": "51",
    "html": "<div class=\"num\"><div class=\"numn\">01</div><div><div class=\"numt\">Is this window about your work, your money, your home, or one particular person?</div><div class=\"numd\">Usually it’s one of them. Sometimes it’s all of them at once, and that’s the window you wait 12 years for. Aim at the right one and these 2 weeks can change your year.</div></div></div>",
    "text": "01 Is this window about your work, your money, your home, or one particular person? Usually it’s one of them. Sometimes it’s all of them at once, and that’s the window you wait 12 years for. Aim at the right one and these 2 weeks can change your year."
   },
   {
    "id": "52",
    "html": "<div class=\"num\"><div class=\"numn\">02</div><div><div class=\"numt\">Which day is the big one?</div><div class=\"numd\">Jupiter peaks on one day. Make your move that day and you get the best answer you’ll get all year. Make it early and you don’t.</div></div></div>",
    "text": "02 Which day is the big one? Jupiter peaks on one day. Make your move that day and you get the best answer you’ll get all year. Make it early and you don’t."
   },
   {
    "id": "53",
    "html": "<div class=\"num\" style=\"border-bottom:none\"><div class=\"numn\">03</div><div><div class=\"numt\">Which days are for making your move, and which days are for waiting?</div><div class=\"numd\">Venus goes backward for 6 weeks right after your big day, and anything you lock in while it’s backward tends to come undone. Your report marks those days, so you know when to go for it and when to hold off.</div></div></div>",
    "text": "03 Which days are for making your move, and which days are for waiting? Venus goes backward for 6 weeks right after your big day, and anything you lock in while it’s backward tends to come undone. Your report marks those days, so you know when to go for it and when to hold off."
   },
   {
    "id": "54",
    "html": "<div class=\"sh\">Your Transformation Window Report</div>",
    "text": "Your Transformation Window Report"
   },
   {
    "id": "55",
    "html": "<p class=\"p\">All of it read off your own chart, written for you, in your inbox within 24 hours.</p>",
    "text": "All of it read off your own chart, written for you, in your inbox within 24 hours."
   },
   {
    "id": "56",
    "html": "<div class=\"bul\">\n  <div><strong>Every part of your life this window lights up.</strong> Work, money, home, one particular person, and in some charts 2 or 3 of them at once. The strongest comes first, and it’s what you go after on day one.</div>\n  <div><strong>Your big day.</strong> The one day out of 12 when a yes comes easiest. The day to send the email, make the call, say the number out loud.</div>\n  <div><strong>Your big day, hour by hour.</strong> When to make your move, and what to have wrapped up before the day is over.</div>\n  <div><strong>What this window says yes to.</strong> The kind of ask it’s built for, so you spend your 12 days going after the right thing instead of guessing.</div>\n  <div><strong>Your go days and your wait days.</strong> Which days of your window are for making your move, and which days to hold off, on one calendar.</div>\n  <div><strong>How to be ready before it opens.</strong> What to line up in the days before, so when the door swings open you walk straight through it.</div>\n</div>",
    "text": "Every part of your life this window lights up. Work, money, home, one particular person, and in some charts 2 or 3 of them at once. The strongest comes first, and it’s what you go after on day one. Your big day. The one day out of 12 when a yes comes easiest. The day to send the email, make the call, say the number out loud. Your big day, hour by hour. When to make your move, and what to have wrapped up before the day is over. What this window says yes to. The kind of ask it’s built for, so you spend your 12 days going after the right thing instead of guessing. Your go days and your wait days. Which days of your window are for making your move, and which days to hold off, on one calendar. How to be ready before it opens. What to line up in the days before, so when the door swings open you walk straight through it."
   },
   {
    "id": "57",
    "html": "<div class=\"rule\"></div>",
    "text": ""
   },
   {
    "id": "58",
    "html": "<div class=\"img\" style=\"height:300px\">Image</div>",
    "text": "Image"
   },
   {
    "id": "59",
    "html": "<div class=\"h1\" style=\"font-size:52px\">$39</div>",
    "text": "$39"
   },
   {
    "id": "60",
    "html": "<p class=\"p\">$39, one time.</p>",
    "text": "$39, one time."
   },
   {
    "id": "61",
    "html": "<p class=\"p\">An hour with me or anyone else who does this properly starts at $200, and most of us are booked solid through October. I can’t sit down with everyone. I can do this.</p>",
    "text": "An hour with me or anyone else who does this properly starts at $200, and most of us are booked solid through October. I can’t sit down with everyone. I can do this."
   },
   {
    "id": "62",
    "html": "<p class=\"p\">$39 gets you the only version of this window that’s actually yours. Which part of your life it opens, which day to make your move, and which days to hold off. Written from your chart, not from your star sign.</p>",
    "text": "$39 gets you the only version of this window that’s actually yours. Which part of your life it opens, which day to make your move, and which days to hold off. Written from your chart, not from your star sign."
   },
   {
    "id": "63",
    "html": "<p class=\"p\"><span class=\"fill\">[WINDOW_STATE: It opens in 13 days]</span>. After it closes, the next one like it is 2038.</p>",
    "text": "[WINDOW_STATE: It opens in 13 days] . After it closes, the next one like it is 2038."
   },
   {
    "id": "64",
    "html": "<div class=\"cta\">» Get my Transformation Window Report · $39</div>",
    "text": "» Get my Transformation Window Report · $39"
   },
   {
    "id": "65",
    "html": "<div class=\"pen\" style=\"padding:22px 24px;display:flex;flex-direction:column;gap:12px\">\n  <div class=\"lab\" style=\"color:#9c3d22\">If it doesn’t ring true, you keep the report and you keep your money</div>\n  <p class=\"p\">Your report also covers the window that already came and went in August, so the first thing you read is a part of your own life you’ve already lived through.</p>\n  <p class=\"p\">If it doesn’t ring true, one email within 60 days puts the $39 back on your card and you keep the report. No forms, no back and forth. I read those emails myself.</p>\n</div>",
    "text": "If it doesn’t ring true, you keep the report and you keep your money Your report also covers the window that already came and went in August, so the first thing you read is a part of your own life you’ve already lived through. If it doesn’t ring true, one email within 60 days puts the $39 back on your card and you keep the report. No forms, no back and forth. I read those emails myself."
   },
   {
    "id": "66",
    "html": "<div class=\"sh\">What people did with theirs</div>",
    "text": "What people did with theirs"
   },
   {
    "id": "67",
    "html": "<div class=\"tstbox\">\n  <div class=\"tst\"><div class=\"tstq\">“For 3 years I’ve done everything right and nothing moved, and I’d started to think it was me. Finding out there’s a reason for that, and that a stretch is coming where it finally gives, is the first time I’ve breathed out in a long time.”</div><div class=\"tstn\">Barb S., Toledo OH</div></div>\n  <div class=\"tst\"><div class=\"tstq\">“Mine said home. My husband and I have been going in circles about moving for 2 years and never pulling the trigger. Now I know which 12 days to have that conversation in, and which day. We’re having it on my big day, and for once I’m not dreading it.”</div><div class=\"tstn\">Denise R., Tulsa OK</div></div>\n  <div class=\"tst\"><div class=\"tstq\">“I’ve had a rough year and I’d honestly stopped expecting anything good. Reading that the biggest window in 12 years is opening for me, and that it’s about the one thing I’ve been afraid to hope for, I cried in the parking lot.”</div><div class=\"tstn\">Krystal M., Little Rock AR</div></div>\n  <div class=\"tst\"><div class=\"tstq\">“I’m not a woo person. I bought it because I’m tired of guessing. What I got was a big day circled on my calendar and a reason to finally ask for the thing I keep chickening out on. I feel ready, and I haven’t felt ready for anything in years.”</div><div class=\"tstn\">Carla M., Mesa AZ</div></div>\n  <div class=\"tst\"><div class=\"tstq\">“My daughter thinks I’ve lost it. My big day is on the fridge with a magnet and she keeps asking what happens that day. I told her I do. That’s what happens.”</div><div class=\"tstn\">Marlene T., Spokane WA</div></div>\n  <div class=\"tst\"><div class=\"tstq\">“Mine was about a person. It didn’t say who. I knew who.”</div><div class=\"tstn\">Priya N., Newark NJ</div></div>\n  <div class=\"tst\"><div class=\"tstq\">“My husband thinks it’s nonsense. He also asked me if he has one.”</div><div class=\"tstn\">Joanne K., Dayton OH</div></div>\n</div>",
    "text": "“For 3 years I’ve done everything right and nothing moved, and I’d started to think it was me. Finding out there’s a reason for that, and that a stretch is coming where it finally gives, is the first time I’ve breathed out in a long time.” Barb S., Toledo OH “Mine said home. My husband and I have been going in circles about moving for 2 years and never pulling the trigger. Now I know which 12 days to have that conversation in, and which day. We’re having it on my big day, and for once I’m not dreading it.” Denise R., Tulsa OK “I’ve had a rough year and I’d honestly stopped expecting anything good. Reading that the biggest window in 12 years is opening for me, and that it’s about the one thing I’ve been afraid to hope for, I cried in the parking lot.” Krystal M., Little Rock AR “I’m not a woo person. I bought it because I’m tired of guessing. What I got was a big day circled on my calendar and a reason to finally ask for the thing I keep chickening out on. I feel ready, and I haven’t felt ready for anything in years.” Carla M., Mesa AZ “My daughter thinks I’ve lost it. My big day is on the fridge with a magnet and she keeps asking what happens that day. I told her I do. That’s what happens.” Marlene T., Spokane WA “Mine was about a person. It didn’t say who. I knew who.” Priya N., Newark NJ “My husband thinks it’s nonsense. He also asked me if he has one.” Joanne K., Dayton OH"
   },
   {
    "id": "68",
    "html": "<div class=\"sh\">Nobody can tell you exactly what happens. But I can tell you when to make your move.</div>",
    "text": "Nobody can tell you exactly what happens. But I can tell you when to make your move."
   },
   {
    "id": "69",
    "html": "<p class=\"p\">I’m not going to tell you money shows up, or somebody walks through the door, or that October is your month. In 18 years I’ve never once been able to say that about anybody. The people who say it are the same people who sold you August, and I’d rather you didn’t buy from either of us than buy that.</p>",
    "text": "I’m not going to tell you money shows up, or somebody walks through the door, or that October is your month. In 18 years I’ve never once been able to say that about anybody. The people who say it are the same people who sold you August, and I’d rather you didn’t buy from either of us than buy that."
   },
   {
    "id": "70",
    "html": "<p class=\"p\">What I can tell you is when the wave comes in, how long it stays, and which part of your life it’s coming in on. You still have to paddle. But you get to paddle with the ocean behind you for 12 days, instead of against it for another year.</p>",
    "text": "What I can tell you is when the wave comes in, how long it stays, and which part of your life it’s coming in on. You still have to paddle. But you get to paddle with the ocean behind you for 12 days, instead of against it for another year."
   },
   {
    "id": "71",
    "html": "<p class=\"p\"><strong>The timing is mine to give you. The ride is yours.</strong></p>",
    "text": "The timing is mine to give you. The ride is yours."
   },
   {
    "id": "72",
    "html": "<div style=\"height:2px;background:#2f2620\"></div>",
    "text": ""
   },
   {
    "id": "73",
    "html": "<div class=\"sh\" style=\"font-size:28px\">Your Transformation Window <span class=\"fill\">[WINDOW_STATE: opens in 13 days]</span></div>",
    "text": "Your Transformation Window [WINDOW_STATE: opens in 13 days]"
   },
   {
    "id": "74",
    "html": "<p class=\"p\">One has already opened and closed on you since August, and you most likely found out just now.</p>",
    "text": "One has already opened and closed on you since August, and you most likely found out just now."
   },
   {
    "id": "75",
    "html": "<p class=\"p\">This one opens whether you’re ready or not, lasts 12 days, and closes the same way.</p>",
    "text": "This one opens whether you’re ready or not, lasts 12 days, and closes the same way."
   },
   {
    "id": "76",
    "html": "<p class=\"p\"><strong>It’s a Jupiter window, and the next one of those is 12 years away. I’d hate for you to find out about it in November.</strong></p>",
    "text": "It’s a Jupiter window, and the next one of those is 12 years away. I’d hate for you to find out about it in November."
   },
   {
    "id": "77",
    "html": "<div class=\"cta\">» Get my Transformation Window Report · $39</div>",
    "text": "» Get my Transformation Window Report · $39"
   },
   {
    "id": "78",
    "html": "<p class=\"small\" style=\"text-align:center\">One-time payment · Worked out from your chart · Full refund within 60 days</p>",
    "text": "One-time payment · Worked out from your chart · Full refund within 60 days"
   },
   {
    "id": "79",
    "html": "<div class=\"band\">\n  <p class=\"p\"><strong>P.S.</strong> If you take one thing away from this, take this. The best day of your window is the day to make your move. It’s also the day Venus turns around, so it’s not the day to make anything final. Your report marks both, on purpose.</p>\n</div>",
    "text": "P.S. If you take one thing away from this, take this. The best day of your window is the day to make your move. It’s also the day Venus turns around, so it’s not the day to make anything final. Your report marks both, on purpose."
   },
   {
    "id": "80",
    "html": "<div class=\"rule\"></div>",
    "text": ""
   },
   {
    "id": "81",
    "html": "<p class=\"small\">Astrology is offered for entertainment and personal reflection. The dates are astronomy and every one of them can be checked. What happens on them is not something we predict, and none of this is a substitute for medical, legal, financial or psychological advice.</p>",
    "text": "Astrology is offered for entertainment and personal reflection. The dates are astronomy and every one of them can be checked. What happens on them is not something we predict, and none of this is a substitute for medical, legal, financial or psychological advice."
   }
  ]
 },
 "sales": {
  "title": "Sales page",
  "sub": "Shown after signup, with her name and birth date filled in.",
  "blocks": [
   {
    "id": "01",
    "html": "<div style=\"display:flex;justify-content:space-between;align-items:center\">\n  <div class=\"strip\">PREPARED FOR <span class=\"fill\">[NAME: SARAH]</span></div>\n  <div class=\"strip\">YOUR WINDOW <span class=\"fill\">[WINDOW_STATE: OPENS IN 13 DAYS]</span></div>\n</div>",
    "text": "PREPARED FOR [NAME: SARAH] YOUR WINDOW [WINDOW_STATE: OPENS IN 13 DAYS]"
   },
   {
    "id": "02",
    "html": "<div class=\"rule\"></div>",
    "text": ""
   },
   {
    "id": "03",
    "html": "<div class=\"h1\">A rare Transformation Window is opening in your chart. It’s the biggest one you’ll get for the next 12 years.</div>",
    "text": "A rare Transformation Window is opening in your chart. It’s the biggest one you’ll get for the next 12 years."
   },
   {
    "id": "04",
    "html": "<div class=\"dek\" style=\"font-weight:700;font-size:22px;color:#2f2620\"><span class=\"fill\">[NAME: Sarah]</span>, a Transformation Window is the few days when a planet crosses the spot the August eclipse marked in your birth chart. While it’s open, what’s been stuck all year finally moves. Yours <span class=\"fill\">[WINDOW_STATE: opens in 13 days]</span>, lasts 12 days, and belongs to Jupiter, the planet that gets you a yes. Jupiter won’t be back until 2038.</div>",
    "text": "[NAME: Sarah] , a Transformation Window is the few days when a planet crosses the spot the August eclipse marked in your birth chart. While it’s open, what’s been stuck all year finally moves. Yours [WINDOW_STATE: opens in 13 days] , lasts 12 days, and belongs to Jupiter, the planet that gets you a yes. Jupiter won’t be back until 2038."
   },
   {
    "id": "05",
    "html": "<div class=\"stat\">\n  <div><span class=\"statlab\">WINDOW</span><span class=\"statval\"><span class=\"fill\">[WINDOW_STATE: Opens in 13 days]</span></span></div>\n  <div><span class=\"statlab\">LENGTH</span><span class=\"statval\">12 days</span></div>\n  <div><span class=\"statlab\">PLANET</span><span class=\"statval\">Jupiter</span></div>\n  <div><span class=\"statlab\">NEXT ONE</span><span class=\"statval\">2038</span></div>\n</div>",
    "text": "WINDOW [WINDOW_STATE: Opens in 13 days] LENGTH 12 days PLANET Jupiter NEXT ONE 2038"
   },
   {
    "id": "06",
    "html": "<div class=\"img\" style=\"height:340px\">Image</div>",
    "text": "Image"
   },
   {
    "id": "07",
    "html": "<p class=\"p\"><span class=\"fill\">[CONTACT_LINE: Your Venus sits almost exactly on the spot the eclipse marked, which is why this window lands harder on you than on most people]</span></p>",
    "text": "[CONTACT_LINE: Your Venus sits almost exactly on the spot the eclipse marked, which is why this window lands harder on you than on most people]"
   },
   {
    "id": "08",
    "html": "<p class=\"p\">Your Transformation Window Report is built from your birth date, <span class=\"fill\">[BIRTH_DATE: March 4, 1979]</span>. It tells you what this window is about, which day is your big one, and which days to hold off.</p>",
    "text": "Your Transformation Window Report is built from your birth date, [BIRTH_DATE: March 4, 1979] . It tells you what this window is about, which day is your big one, and which days to hold off."
   },
   {
    "id": "09",
    "html": "<div class=\"cta\">» Get my Transformation Window Report · $39</div>",
    "text": "» Get my Transformation Window Report · $39"
   },
   {
    "id": "10",
    "html": "<p class=\"small\" style=\"text-align:center\">Worked out from your chart · In your inbox within 24 hours · Full refund within 60 days</p>",
    "text": "Worked out from your chart · In your inbox within 24 hours · Full refund within 60 days"
   },
   {
    "id": "11",
    "html": "<div style=\"height:2px;background:#2f2620\"></div>",
    "text": ""
   },
   {
    "id": "12",
    "html": "<div class=\"sh\">The 2 weeks a year when everything says yes</div>",
    "text": "The 2 weeks a year when everything says yes"
   },
   {
    "id": "13",
    "html": "<p class=\"p\">There are weeks when you finally say the thing you’ve been rehearsing and get a yes on the spot. The person who went quiet calls back. The money lands the week you need it. You didn’t work harder or get smarter. It just went.</p>",
    "text": "There are weeks when you finally say the thing you’ve been rehearsing and get a yes on the spot. The person who went quiet calls back. The money lands the week you need it. You didn’t work harder or get smarter. It just went."
   },
   {
    "id": "14",
    "html": "<p class=\"p\">And there are weeks when the same you, with the same pitch and the same effort, gets nothing. Doors that were wide open a month ago won’t budge, and there’s no good reason why.</p>",
    "text": "And there are weeks when the same you, with the same pitch and the same effort, gets nothing. Doors that were wide open a month ago won’t budge, and there’s no good reason why."
   },
   {
    "id": "15",
    "html": "<p class=\"p\">Those good weeks aren’t luck. They’re Transformation Windows. They start on a set day and end on a set day, and your chart knew both before you did.</p>",
    "text": "Those good weeks aren’t luck. They’re Transformation Windows. They start on a set day and end on a set day, and your chart knew both before you did."
   },
   {
    "id": "16",
    "html": "<p class=\"p\"><strong>You get 3 or 4 a year. They’re the only weeks when pushing actually pays. And the biggest one you’ll get for the next 12 years <span class=\"fill\">[WINDOW_STATE: opens in 13 days]</span>.</strong></p>",
    "text": "You get 3 or 4 a year. They’re the only weeks when pushing actually pays. And the biggest one you’ll get for the next 12 years [WINDOW_STATE: opens in 13 days] ."
   },
   {
    "id": "17",
    "html": "<div class=\"sh\">What actually happened on August 12</div>",
    "text": "What actually happened on August 12"
   },
   {
    "id": "18",
    "html": "<p class=\"p\">Nothing happens on the night of an eclipse. It marks a spot in the sky and waits. Things happen later, when a planet crosses that spot. On August 12, no planet was anywhere near it.</p>",
    "text": "Nothing happens on the night of an eclipse. It marks a spot in the sky and waits. Things happen later, when a planet crosses that spot. On August 12, no planet was anywhere near it."
   },
   {
    "id": "19",
    "html": "<p class=\"p\">Every app posted about the eclipse anyway, because that’s the night people pay attention. Millions of people set an intention, lit a candle, and waited. Nothing was there to catch it.</p>",
    "text": "Every app posted about the eclipse anyway, because that’s the night people pay attention. Millions of people set an intention, lit a candle, and waited. Nothing was there to catch it."
   },
   {
    "id": "20",
    "html": "<p class=\"p\"><strong>August 12 was the wrong day to wait for. The right days are when Jupiter reaches the spot, and that’s your window. It <span class=\"fill\">[WINDOW_STATE: opens in 13 days]</span>.</strong></p>",
    "text": "August 12 was the wrong day to wait for. The right days are when Jupiter reaches the spot, and that’s your window. It [WINDOW_STATE: opens in 13 days] ."
   },
   {
    "id": "21",
    "html": "<div class=\"sh\">Jupiter is the planet that gets you a yes, and it’s the one crossing your spot</div>",
    "text": "Jupiter is the planet that gets you a yes, and it’s the one crossing your spot"
   },
   {
    "id": "22",
    "html": "<p class=\"p\">Every planet that crosses your eclipse spot does something different while it’s there. Mars picks fights. Saturn charges rent. Jupiter is the planet of more. More room, more yes, more luck than you’ve had all year, and it hands it over without asking for anything first.</p>",
    "text": "Every planet that crosses your eclipse spot does something different while it’s there. Mars picks fights. Saturn charges rent. Jupiter is the planet of more. More room, more yes, more luck than you’ve had all year, and it hands it over without asking for anything first."
   },
   {
    "id": "23",
    "html": "<p class=\"p\">Jupiter is slow. It takes 12 years to get around the sky, so it reaches this spot in your chart once every 12 years. The last time was the fall of 2014. Think back to that fall. If something big changed for you then, that was Jupiter on this same spot. After this pass it won’t be back until 2038, when you’ll be <span class=\"fill\">[AGE_2038: 59]</span>.</p>",
    "text": "Jupiter is slow. It takes 12 years to get around the sky, so it reaches this spot in your chart once every 12 years. The last time was the fall of 2014. Think back to that fall. If something big changed for you then, that was Jupiter on this same spot. After this pass it won’t be back until 2038, when you’ll be [AGE_2038: 59] ."
   },
   {
    "id": "24",
    "html": "<p class=\"p\">One more thing lands the same day, and it’s a warning. Venus, the planet that rules what you commit to, starts going backward for 6 weeks a few hours before Jupiter peaks. Anything you lock in while Venus is backward tends to come undone. So your best day to go for it is also the worst day to make anything final, and the only way to tell those days apart is to know which is which.</p>",
    "text": "One more thing lands the same day, and it’s a warning. Venus, the planet that rules what you commit to, starts going backward for 6 weeks a few hours before Jupiter peaks. Anything you lock in while Venus is backward tends to come undone. So your best day to go for it is also the worst day to make anything final, and the only way to tell those days apart is to know which is which."
   },
   {
    "id": "25",
    "html": "<p class=\"p\"><strong>12 days out of 12 years, and the best day and the riskiest day fall on the same date. That’s why this window needs a map.</strong></p>",
    "text": "12 days out of 12 years, and the best day and the riskiest day fall on the same date. That’s why this window needs a map."
   },
   {
    "id": "26",
    "html": "<div class=\"sh\"><span class=\"fill\">[NAME: Sarah]</span>, a smaller window has already closed on you since August</div>",
    "text": "[NAME: Sarah] , a smaller window has already closed on you since August"
   },
   {
    "id": "27",
    "html": "<p class=\"p\">Jupiter isn’t the first planet to cross the spot. Mercury went over on August 20 and was gone in 20 hours. That was a Transformation Window too. A small one, a fast one, but real.</p>",
    "text": "Jupiter isn’t the first planet to cross the spot. Mercury went over on August 20 and was gone in 20 hours. That was a Transformation Window too. A small one, a fast one, but real."
   },
   {
    "id": "28",
    "html": "<p class=\"p\">If something in your life picked up speed in the middle of August and then went quiet before you could get your arms around it, that was a window shutting with you still standing in it.</p>",
    "text": "If something in your life picked up speed in the middle of August and then went quiet before you could get your arms around it, that was a window shutting with you still standing in it."
   },
   {
    "id": "29",
    "html": "<div class=\"wrow\"><div class=\"wn\">AUG 20–21</div><div class=\"wd\">Mercury · 20 hours</div><div class=\"wsGone\">MISSED</div></div>",
    "text": "AUG 20–21 Mercury · 20 hours MISSED"
   },
   {
    "id": "30",
    "html": "<div class=\"wrow\"><div class=\"wn\"><span class=\"fill\">[WINDOW_STATE: IN 13 DAYS]</span></div><div class=\"wd\">Jupiter · 12 days · the big one</div><div class=\"wsLive\">YOURS TO USE</div></div>",
    "text": "[WINDOW_STATE: IN 13 DAYS] Jupiter · 12 days · the big one YOURS TO USE"
   },
   {
    "id": "31",
    "html": "<p class=\"p\"><strong>The one you missed lasted 20 hours. The one in front of you lasts 12 days, and it’s the only Jupiter window you’ll get on this spot until 2038.</strong></p>",
    "text": "The one you missed lasted 20 hours. The one in front of you lasts 12 days, and it’s the only Jupiter window you’ll get on this spot until 2038."
   },
   {
    "id": "32",
    "html": "<div class=\"sh\">One of your 12 days is the big one, and your report tells you which</div>",
    "text": "One of your 12 days is the big one, and your report tells you which"
   },
   {
    "id": "33",
    "html": "<p class=\"p\">Jupiter peaks on one day. The other 11 are the build-up and the fade. Make your move on the peak day and you get the best answer you’ll get all year. Make it 2 days early and it’s just another Tuesday. Your report names your big day, down to the hour, so you’re not guessing.</p>",
    "text": "Jupiter peaks on one day. The other 11 are the build-up and the fade. Make your move on the peak day and you get the best answer you’ll get all year. Make it 2 days early and it’s just another Tuesday. Your report names your big day, down to the hour, so you’re not guessing."
   },
   {
    "id": "34",
    "html": "<p class=\"p\">From your big day on, Venus is going backward. That half of the window is for going after what you want, not for locking anything in. Whatever you make final while Venus is backward has a way of coming undone by November. Your report marks those days too.</p>",
    "text": "From your big day on, Venus is going backward. That half of the window is for going after what you want, not for locking anything in. Whatever you make final while Venus is backward has a way of coming undone by November. Your report marks those days too."
   },
   {
    "id": "35",
    "html": "<p class=\"p\">And the window opens on one part of your life, whether that’s your work, your money, your home, or one particular person. Sometimes it’s more than one at once, and those are the windows people remember for years.</p>",
    "text": "And the window opens on one part of your life, whether that’s your work, your money, your home, or one particular person. Sometimes it’s more than one at once, and those are the windows people remember for years."
   },
   {
    "id": "36",
    "html": "<p class=\"p\"><strong>Push on the wrong part of your life and the best 2 weeks of your year go to waste. Push on the right one, on the right day, and it gives.</strong></p>",
    "text": "Push on the wrong part of your life and the best 2 weeks of your year go to waste. Push on the right one, on the right day, and it gives."
   },
   {
    "id": "37",
    "html": "<div class=\"sh\">What’s in your Transformation Window Report</div>",
    "text": "What’s in your Transformation Window Report"
   },
   {
    "id": "38",
    "html": "<div class=\"num\"><div class=\"numn\">01</div><div><div class=\"numt\">Which part of your life this window opens</div><div class=\"numd\">Your work, your money, your home, or one particular person. If it’s more than one, the strongest comes first, so you know exactly where to aim from day one.</div><div class=\"lab\" style=\"margin-top:8px\">12 DAYS · <span class=\"fill\">[WINDOW_STATE: OPENS IN 13 DAYS]</span></div></div></div>",
    "text": "01 Which part of your life this window opens Your work, your money, your home, or one particular person. If it’s more than one, the strongest comes first, so you know exactly where to aim from day one. 12 DAYS · [WINDOW_STATE: OPENS IN 13 DAYS]"
   },
   {
    "id": "39",
    "html": "<div class=\"num\"><div class=\"numn\">02</div><div><div class=\"numt\">Your big day</div><div class=\"numd\">The one day out of 12 to make your move, and the best hours of that day to make it.</div><div class=\"lab\" style=\"margin-top:8px\">ONE DAY · NAMED IN YOUR REPORT</div></div></div>",
    "text": "02 Your big day The one day out of 12 to make your move, and the best hours of that day to make it. ONE DAY · NAMED IN YOUR REPORT"
   },
   {
    "id": "40",
    "html": "<div class=\"num\"><div class=\"numn\">03</div><div><div class=\"numt\">Your go days and your wait days</div><div class=\"numd\">Which days of your window are for making your move, and which days to hold off before you make anything final. All on one calendar.</div><div class=\"lab\" style=\"margin-top:8px\">6 WEEKS · MARKED IN YOUR REPORT</div></div></div>",
    "text": "03 Your go days and your wait days Which days of your window are for making your move, and which days to hold off before you make anything final. All on one calendar. 6 WEEKS · MARKED IN YOUR REPORT"
   },
   {
    "id": "41",
    "html": "<div class=\"num\"><div class=\"numn\">04</div><div><div class=\"numt\">Your 2 follow-up windows</div><div class=\"numd\">Jupiter doesn’t cross your spot once. It crosses it 3 times in 8 months, and this is the first. It comes back in February and again in May, and then it’s gone for 12 years. Whatever you start in this window gets a second push in February and settles in May. Both of those windows are in your report, so you know when the next 2 pushes come and what to have ready for each.</div><div class=\"lab\" style=\"margin-top:8px\">FEBRUARY AND MAY · 2 MORE WINDOWS</div></div></div>",
    "text": "04 Your 2 follow-up windows Jupiter doesn’t cross your spot once. It crosses it 3 times in 8 months, and this is the first. It comes back in February and again in May, and then it’s gone for 12 years. Whatever you start in this window gets a second push in February and settles in May. Both of those windows are in your report, so you know when the next 2 pushes come and what to have ready for each. FEBRUARY AND MAY · 2 MORE WINDOWS"
   },
   {
    "id": "42",
    "html": "<div class=\"num\" style=\"border-bottom:none\"><div class=\"numn\">05</div><div><div class=\"numt\">How to be ready before it opens</div><div class=\"numd\">What to line up in the days before, and what to have wrapped up before the peak day is over, so when the door swings open you’re already standing at it.</div><div class=\"lab\" style=\"margin-top:8px\">THE WEEK BEFORE · THE PEAK DAY</div></div></div>",
    "text": "05 How to be ready before it opens What to line up in the days before, and what to have wrapped up before the peak day is over, so when the door swings open you’re already standing at it. THE WEEK BEFORE · THE PEAK DAY"
   },
   {
    "id": "43",
    "html": "<div class=\"rule\"></div>",
    "text": ""
   },
   {
    "id": "44",
    "html": "<div class=\"h1\" style=\"font-size:52px\">$39</div>",
    "text": "$39"
   },
   {
    "id": "45",
    "html": "<p class=\"p\">$39, once. Nothing else, ever.</p>",
    "text": "$39, once. Nothing else, ever."
   },
   {
    "id": "46",
    "html": "<p class=\"p\">An hour with a working astrologer runs $150 to $300, if you can get one before the window closes, and most of that hour goes to things you don’t need right now. You don’t need your whole chart explained. You need to know what these 12 days are about, which day is the big one, and which days to hold off. That’s what the report does, for less than a dinner out.</p>",
    "text": "An hour with a working astrologer runs $150 to $300, if you can get one before the window closes, and most of that hour goes to things you don’t need right now. You don’t need your whole chart explained. You need to know what these 12 days are about, which day is the big one, and which days to hold off. That’s what the report does, for less than a dinner out."
   },
   {
    "id": "47",
    "html": "<p class=\"p\">The report costs the same whenever you order it. The window doesn’t. Every day between now and the peak is one you either get to use or don’t.</p>",
    "text": "The report costs the same whenever you order it. The window doesn’t. Every day between now and the peak is one you either get to use or don’t."
   },
   {
    "id": "48",
    "html": "<div class=\"cta\">» Get my Transformation Window Report · $39</div>",
    "text": "» Get my Transformation Window Report · $39"
   },
   {
    "id": "49",
    "html": "<div class=\"pen\" style=\"padding:22px 24px;display:flex;flex-direction:column;gap:12px\">\n  <div class=\"lab\" style=\"color:#9c3d22\">If it doesn’t ring true, you keep the report and your money</div>\n  <p class=\"p\">One email within 60 days puts the $39 back on your card. You keep the report. No form, no questions, no waiting on hold.</p>\n</div>",
    "text": "If it doesn’t ring true, you keep the report and your money One email within 60 days puts the $39 back on your card. You keep the report. No form, no questions, no waiting on hold."
   },
   {
    "id": "50",
    "html": "<div class=\"sh\">What the report won’t say</div>",
    "text": "What the report won’t say"
   },
   {
    "id": "51",
    "html": "<p class=\"p\">It won’t say money lands on a Tuesday or that someone walks through the door. Nobody honest can say that, and the people who do are the ones who sold you August. It tells you when the door is open, which door, and which day to walk through. What’s on the other side is yours.</p>",
    "text": "It won’t say money lands on a Tuesday or that someone walks through the door. Nobody honest can say that, and the people who do are the ones who sold you August. It tells you when the door is open, which door, and which day to walk through. What’s on the other side is yours."
   },
   {
    "id": "52",
    "html": "<div class=\"sh\">Before you order</div>",
    "text": "Before you order"
   },
   {
    "id": "53",
    "html": "<p class=\"q\">I’m reading this after the window already opened.</p>",
    "text": "I’m reading this after the window already opened."
   },
   {
    "id": "54",
    "html": "<p class=\"p\">Then you’re inside it right now, and your big day is most likely still ahead of you. The report lands within 24 hours. Every day you wait is one of the 12 spent guessing.</p>",
    "text": "Then you’re inside it right now, and your big day is most likely still ahead of you. The report lands within 24 hours. Every day you wait is one of the 12 spent guessing."
   },
   {
    "id": "55",
    "html": "<p class=\"q\">What if nothing happens?</p>",
    "text": "What if nothing happens?"
   },
   {
    "id": "56",
    "html": "<p class=\"p\">A window makes things easier to move. It doesn’t move them for you. If you sit through all 12 days and ask for nothing, it closes the same as any other 2 weeks. That’s the one outcome the report can’t protect you from.</p>",
    "text": "A window makes things easier to move. It doesn’t move them for you. If you sit through all 12 days and ask for nothing, it closes the same as any other 2 weeks. That’s the one outcome the report can’t protect you from."
   },
   {
    "id": "57",
    "html": "<div class=\"sh\">What people did with theirs</div>",
    "text": "What people did with theirs"
   },
   {
    "id": "58",
    "html": "<div class=\"tstbox\">\n  <div class=\"tst\"><div class=\"tstq\">“I always figured the good weeks were luck and you just ride them while they last. Finding out they have a beginning and an end, and that you can see the next one coming, is the most in control of my own life I’ve felt in years.”</div><div class=\"tstn\">Renee W., Boise ID</div></div>\n  <div class=\"tst\"><div class=\"tstq\">“I did the math on 12 years and just sat there. 2014 was the year my whole life turned over, and I had no idea anything was open. This time I’m walking in with my eyes open.”</div><div class=\"tstn\">Gail F., Wichita KS</div></div>\n  <div class=\"tst\"><div class=\"tstq\">“I’ve been sitting on the same idea for years because it never felt like the right time. Turns out there is a right time, it’s short, and it’s almost here. I’ve never felt this sure about something I haven’t done yet.”</div><div class=\"tstn\">Tamika J., Charlotte NC</div></div>\n  <div class=\"tst\"><div class=\"tstq\">“The wait days hit home. I’ve jumped at things in a good week and paid for it for a year. Knowing which days to hold back is worth more to me than the big day.”</div><div class=\"tstn\">Deb H., Grand Rapids MI</div></div>\n  <div class=\"tst\"><div class=\"tstq\">“I’m 54 and I’ve felt invisible for a while. Reading that a window this big was opening for me, me specifically, made me sit up straight. My big day is circled and I’m wearing the red dress.”</div><div class=\"tstn\">Lorraine P., Sacramento CA</div></div>\n  <div class=\"tst\"><div class=\"tstq\">“I haven’t told anybody I bought this. I’ve also already booked the day off work.”</div><div class=\"tstn\">Yesenia R., Tucson AZ</div></div>\n</div>",
    "text": "“I always figured the good weeks were luck and you just ride them while they last. Finding out they have a beginning and an end, and that you can see the next one coming, is the most in control of my own life I’ve felt in years.” Renee W., Boise ID “I did the math on 12 years and just sat there. 2014 was the year my whole life turned over, and I had no idea anything was open. This time I’m walking in with my eyes open.” Gail F., Wichita KS “I’ve been sitting on the same idea for years because it never felt like the right time. Turns out there is a right time, it’s short, and it’s almost here. I’ve never felt this sure about something I haven’t done yet.” Tamika J., Charlotte NC “The wait days hit home. I’ve jumped at things in a good week and paid for it for a year. Knowing which days to hold back is worth more to me than the big day.” Deb H., Grand Rapids MI “I’m 54 and I’ve felt invisible for a while. Reading that a window this big was opening for me, me specifically, made me sit up straight. My big day is circled and I’m wearing the red dress.” Lorraine P., Sacramento CA “I haven’t told anybody I bought this. I’ve also already booked the day off work.” Yesenia R., Tucson AZ"
   },
   {
    "id": "59",
    "html": "<div style=\"height:2px;background:#2f2620\"></div>",
    "text": ""
   },
   {
    "id": "60",
    "html": "<div class=\"sh\" style=\"font-size:28px\">Your window <span class=\"fill\">[WINDOW_STATE: opens in 13 days]</span>, whether you’re ready or not</div>",
    "text": "Your window [WINDOW_STATE: opens in 13 days] , whether you’re ready or not"
   },
   {
    "id": "61",
    "html": "<p class=\"p\">12 days when life says yes. One day inside them that matters more than the rest. Then it shuts, and Jupiter doesn’t come back to this spot until you’re <span class=\"fill\">[AGE_2038: 59]</span>.</p>",
    "text": "12 days when life says yes. One day inside them that matters more than the rest. Then it shuts, and Jupiter doesn’t come back to this spot until you’re [AGE_2038: 59] ."
   },
   {
    "id": "62",
    "html": "<p class=\"p\">You can walk in knowing your big day, your wait days, and what to go after. Or you can find out what it was about in November, the way most people do.</p>",
    "text": "You can walk in knowing your big day, your wait days, and what to go after. Or you can find out what it was about in November, the way most people do."
   },
   {
    "id": "63",
    "html": "<p class=\"p\"><strong>The report is $39. The window is once every 12 years.</strong></p>",
    "text": "The report is $39. The window is once every 12 years."
   },
   {
    "id": "64",
    "html": "<div class=\"cta\">» Get my Transformation Window Report · $39</div>",
    "text": "» Get my Transformation Window Report · $39"
   },
   {
    "id": "65",
    "html": "<p class=\"small\" style=\"text-align:center\">One-time payment · Worked out from your chart · Full refund within 60 days</p>",
    "text": "One-time payment · Worked out from your chart · Full refund within 60 days"
   },
   {
    "id": "66",
    "html": "<div class=\"band\">\n  <p class=\"p\"><strong>P.S.</strong> One window already came and went in August, in 20 hours, while you had no idea. This one lasts 12 days, it’s the only Jupiter window you’ll get on this spot until 2038, and the day it opens, it starts counting down whether you’re ready or not.</p>\n</div>",
    "text": "P.S. One window already came and went in August, in 20 hours, while you had no idea. This one lasts 12 days, it’s the only Jupiter window you’ll get on this spot until 2038, and the day it opens, it starts counting down whether you’re ready or not."
   },
   {
    "id": "67",
    "html": "<div class=\"rule\"></div>",
    "text": ""
   },
   {
    "id": "68",
    "html": "<p class=\"small\">Astrology is offered for entertainment and personal reflection. The dates are astronomy and every one of them can be checked. What happens on them is not something we predict, and none of this is a substitute for medical, legal, financial or psychological advice.</p>",
    "text": "Astrology is offered for entertainment and personal reflection. The dates are astronomy and every one of them can be checked. What happens on them is not something we predict, and none of this is a substitute for medical, legal, financial or psychological advice."
   }
  ]
 }
};
